#!/usr/bin/perl -w
#===============================================================================
#
#        Li Xue (), me.lixue@gmail.com
#        11/24/2016 04:53:02 PM
#
#  DESCRIPTION: Generate the resi number map file between template 1 and query
#        INPUT 1 (template 1 rec/lig pdb)
#        INPUT 2 (hhpred file generated by Mick)
#        # HHPRED&PBLAST
#        # Iteration: 1
#        # Query: 1m9xE
#        # Database: /home/mwalter/project/v0.0.02/projectfiles/databases/pdb70HMMs
#        # Fields: subject ids, query length, subject length, query seq, subject seq, q. start, q. end, s. start, s. end, bit score, evalue, alignment length, % identity, % positives, similarity, HHpredprob, query acc.
#        # 83 hits found
#
#         gi|530537729|pdb|4LQW|A;gi|530537729|pdb|4LQW|A;gi|530537730|pdb|4LQW|B 165 177 VNPTVFFDIAVDGEPLGRVSFELFADKVPKTAENFRALSTGEKGFGYKGSCFHRIIPGFMCQGGDFTRHNGTGGKSIYGEKFEDENFILKHTGPGILSMANAGPNTNGSQFFICTAKTEWLDGKHVVFGKVKEGMNIVEAMERFGSRNGKTSKKITIADCGQL    TNPVVFFDVCADGEPLGRITMELFSNIVPRTAENFRALCTGEKGFGFKNSIFHRVIPDFVCQGGDITKHDGTGGQSIYGDKFEDENFDVKHTGPGLLSMANQGQNTNNSQFVITLKKAEHLDFKHVVFGFVKDGMDTVKKIESFGSPKGSVCRRITITECGQI  2   164 15  177 285.4   1.5E-47 163 66.2    88.9    3.4 100.0   1m9xE
#
#       OUTPUT:
#
#        USAGE: ./genResNumMap_QryTem.pl
#
#===============================================================================

use strict;
use warnings;
use utf8;
use File::Basename;
use PSHomPPI_resiPairs;

my $template_rec_pdbFL = shift @ARGV; #-- template1.rec.4dgeA.pdb
my $hhpredFL = shift @ARGV;
my $template1_rec_ID = shift @ARGV; # '4lqwA,1';

#---- generate template 1's atomResNum file
my $templatePDB_dir = dirname($template_rec_pdbFL);
my $basename = basename($template_rec_pdbFL);
my $resiNumFL_template= "$templatePDB_dir/$basename.atomResNum";
system("/home/lixue/PDB2AtomResNum.pl $template_rec_pdbFL > $resiNumFL_template") ==0 or die ("FAILED: $command:$!");

#----

    my ( $qryID, $totalLengthQry, $blastResults ) =
      &readHHpredOUTPUTFL_userProtDB($hhpredFL);

      my ($homolog, $num) = split(/,/$template1_rec_ID);
   $blastResults->{$homolog}->{$num}->{'LAL'},
                $blastResults->{$homolog}->{$num}->{'bitscore'},
                $blastResults->{$homolog}->{$num}->{'evalue'},
                $blastResults->{$homolog}->{$num}->{'identityS'},
                $blastResults->{$homolog}->{$num}->{'positiveS'},
                $blastResults->{$homolog}->{$num}->{'similarity'},
                $blastResults->{$homolog}->{$num}->{'qstart'},
                $blastResults->{$homolog}->{$num}->{'qend'},
                $blastResults->{$homolog}->{$num}->{'sstart'},
                $blastResults->{$homolog}->{$num}->{'send'},
                $blastResults->{$homolog}->{$num}->{'qseq'},
                $blastResults->{$homolog}->{$num}->{'sseq'},
                $blastResults->{$homolog}->{$num}->{'hhpredProb'}

